version: '2'

services:
  main:
    build:
      context: ./configs/
    container_name: magento2
    ports:
      - 8000:80
    volumes:
      - ../src:/usr/share/nginx/html/
      - ./volumes/nginx-log:/var/log/nginx
    environment:
      - DEBUG=false

  db:
    image: mariadb
    container_name: magento2-db
    volumes:
      - ./volumes/db_volume:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=magento2
